### ISSUE TITLE
The skip to navigation will be confused with skip OVER navigation

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#296]
"This skip link is hidden by default but made visible as soon as it is focused to not confuse sighted keyboard users. As the tutorials are designed in a responsive way, the content is linearized on small screens or when zoom is enabled. In those cases the navigation menu is on the bottom of the page. The skip link is visible to allow all users to jump down to the navigation menus."

Although I like the design of the tutorial pages they are not standard page layout, and as such will be confusing as an example for skip links. Most sites have the navigation menu before main content. Almost never will a designer want to say "skip to main navigation" It should be "skip to main content", and it will skip OVER the navigation to the main content. So I would not refer to these Tutorial skip links as an example of how to do it. I recently had to correct a major web site for skipping to the top navigation, after I had steered them to these tutorials.

Instead create fictitious example, like  http://jimthatcher.com/skipnav.htm

**Comment by yatil** [comment]
Performance and mobile best practices require the actual page content to be first in the page structure. I will add a sentence that will address the navigation-first case but would like to present content first as the best practice, mainly because it saves screen readers an additional click when navigating from page to page.

**Comment by yatil** [comment]
I have added another example.
