### ISSUE TITLE
Empty alt attribute - Image used as part of page design

### ISSUE THREAD

**Issue by sarbbottam** [w3c/wai-tutorials#345]
I guess [Image used as part of page design](https://www.w3.org/WAI/tutorials/images/decorative/#image-used-as-part-of-page-design), first example at [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/) is **an anti-pattern**.

Such images, must not be part of the DOM, rather should be applied via [CSS background/background-image](https://developer.mozilla.org/en-US/docs/Web/CSS/background).

Having said so, I do see the value of empty alt attribute in the remaining examples (2, 3 & 4) at [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/), to avoid repetition.

But are they really decorative images or they are attribution to the corresponding text content?

Thanks!

**Comment by yatil** [comment]
Hi @sarbbottam, thanks for the feedback, indeed the tutorial says:

> The examples below show how to use the alt attribute when decorative images are provided using the `<img>` element. **Where possible, decorative images should be provided using CSS background images instead.**

There is no requirement to use CSS background images instead of `<img>` elements when images are decorative, but I agree that it is best practice. (But sometimes not possible, e.g. when content authors are  putting images in articles for decoration purposes.)

For the remaining examples: Yes, those are decorative as the text would also be understandable without the image displayed.

**Comment by sarbbottam** [comment]
Thanks @yatil
