### ISSUE TITLE
Add aria-orientation="horizontal" to the menu example

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#351]
see http://w3c.github.io/aria/aria/aria.html#menu

**Comment by carmacleod** [comment]
You might want to wait on this one until issue #349 is resolved, because you don't need to explicitly give the orientation on the menubar.
http://w3c.github.io/aria/aria/aria.html#menubar
says:
"Elements with the role menubar have an implicit aria-orientation value of horizontal."

and: http://w3c.github.io/aria/aria/aria.html#implicit_semantics
says:
"Features with implicit WAI-ARIA semantics satisfy WAI-ARIA structural requirements such as required owned elements, required states and properties, etc. and do not require explicit WAI-ARIA semantics to be provided."

**Comment by yatil** [comment]
Good catch, @carmacleod – I just came across it and wanted it captured :-)
