### ISSUE TITLE
carousel spec does not cover keyboard navigation

### ISSUE THREAD

**Issue by amsterdamharu** [w3c/wai-tutorials#377]
https://www.w3.org/WAI/tutorials/carousels/

Navigation between slides can only be accomplished with buttons. I was trying to implement A11Y on a site with a slick slider where there were no buttons. Navigation is accomplished with the arrow keys:

http://jsfiddle.net/tu2xqtej/12/

The only quirk I am facing now is that when navigating slides up (1 to 2 or 2 to 3) and pressing tab it will enter the slide content. When I navigate a slide down (3 to 2) and press tab it will move out of the slide and focus on the "next" button. There is no specification about keyboard navigation so this is not broken unless specification is provided. I would prefer always tab into current slide content when pressing tab after arrow.

The example (slick) has some other issues:
Focus order is not according to the article as l; the order in the example is:
Slide content => left button => right button => pause/play => slide index buttons

Missing a pause/play button as I am unable to find this button in the API (maybe have to add that manually).

I would like to implement these things but was wondering if the standard will be extended to include keyboard navigation between slides.

**Comment by yatil** [comment]
Hi @amsterdamharu,

* As long as the arrow keys are not the only way to move around, it is fine using them. – That said, the focus is on hidden slides at times, which will cause confusion. You need to be careful about the focus management. 

* If your keyboard navigation and order is consistent, the order of the buttons before or after the slides is not that important. You should make clear using an aria-label that this is a carousel region, so that users are aware that those options do exist.

* Capturing left/right arrows might also conflict with assistive technologies in certain circumstances.

I will open a focused issue on the keyboard navigation to track if and how we can add to the keyboard navigation in a future version of the tutorial.

**Comment by yatil** [comment]
(Also note that this is not a specification, but a Tutorial, it is not normative but a demonstration of best practices.)
