### ISSUE TITLE
Carousels Organization

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#379]
<p>
  The organization of the tutorial has changed a bit which is one of the results of the November 2016 F2F meeting: 
</p>

<ul>
  <li>There is now a new <strong><a href="https://w3c.github.io/wai-tutorials/carousels/styling/">Carousel Styling</a></strong> page that aims to bring together all the styling related topics.</li>
  <li>To allow users easy access to the complete <strong><a href="https://w3c.github.io/wai-tutorials/carousels/working-example/">working example</a></strong>, an isolated page was created showing the example (and removing it from the other pages).</li>
</ul>

<p><strong>Question:</strong> What do you think about the new structure of the tutorial?</p>

**Comment by yatil** [comment]
Detailed comments by @nitedog are here:

* Index page: https://github.com/w3c/wai-tutorials/commit/18c7d5a1940dd4efbf17e5f4a254df322235df3a
* Structure page: https://github.com/w3c/wai-tutorials/commit/fcc9eab9443023d73e3197a169a9f0e70bc08bb0
* Styling page: https://github.com/w3c/wai-tutorials/commit/af33247e994dafd9ea36a0c9db195d096e8b4c72
* Functionality page: https://github.com/w3c/wai-tutorials/commit/dcd6b21811b81016724f388bf5b8ef73518d03e6

**Comment by bakkenb** [comment]
I like the new structure. I like that the Working Example is pulled out to a page on its own for a few reasons. First it separates it so that you can find it no matter which sub-page you are in. Second, it is a lot easier to send the link to the working example for others to view. They can view the example and then review the entire tutorial for directions on how to implement.

I also like having the Complete Code sub-page in the navigation as well. Much more simple to find.

I also agree with not numbering these pages in the Navigation area as they are not "steps" in the tutorial, they are the examples, or "results" of an accessible tutorial.

**Comment by bakkenb** [comment]
I don't like the discrepancy between the Navigation page name #1 "Anatomy" and what is in the Carousel Concepts page, "Structure."  I think they should be the same just like the other three are. It confused me at first until I understood where it was going.

**Comment by yatil** [comment]
@bakkenb, thanks for your feedback. 

I tried out the “Anatomy” wording (to be more catchy and in hope it would better describe the page. (@nitedog doesn’t think it does, and I don’t feel strongly, so I will go back to Carousel Structure.

**Comment by yatil** [comment]
Implemented feedback
