### ISSUE TITLE
Transition between first paragraph and second under "General Styling"

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-tutorials#384]
I didn't see the connection between javascript being unavailable and the suggestion that follows in the second paragraph:

Ensure that the carousel content is readable in situations when JavaScript is not available, to improve the robustness of your website.

In the following example the carousel is styled as three individual items in the normal page flow. A semi-transparent background color is used for text containers to guarantee readable contrast when placed on top of the image. (See Design/Contrast.)

[Also, not sure why the "Design/Contrast" like points you back to the same page you're on]

**Comment by yatil** [comment]
Thanks for the feedback. Without JavaScript the three items are in the normal page flow. Some people style carousels in a way that shows the items already stacked, showing only one of the items and making the others inaccessible to everyone.

I will clarify.

> [Also, not sure why the "Design/Contrast" like points you back to the same page you're on]

Because the content (and page) is not ready yet :-) [makes mental note to make future links more clear.]

**Comment by yatil** [comment]
I’ve simplified the whole page in da8a2b4f2e4d7a62390e08d93f06f0dc3428ac5c, removing the text that was unclear.
