### ISSUE TITLE
[Carousels Tutorial] Content of the example

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#400]
I do NOT want this to hold up publishing this tutorial.

For a future update, I would like us to discuss possibly changing the content of "space teddy" to something else as the example for our carousel. I know that we are trying to use completely irrelevant content for the demonstration of our carousel example, but it is hard to take it seriously with such a "cute" example. That sample content strikes me as a little odd or goofy. I am not a developer, but I worry it will have even more of an odd impact on a developer, and they may tune out simply because of the example.

This is only my opinion. If others don't see it this way, I am fine with leaving it as is.

**Again, this is for future consideration only and should not hold up publication as I imagine it would have a large impact on the content of the code snippets throughout.**

**Comment by slhenry** [comment]
**I *strongly* support this.** (I raised this many months ago, I think in context of the Tips.)

For now, can we please at least have less distracting images, even if we don't change the text until later.

**Comment by yatil** [comment]
**I _strongly_ disagree!** There are enough boring examples out there. I have seen people to comment positively on the tutorials because of the examples.

However, knowing that I’m probably alone with that opinion, please submit ideas for less distracting images and examples.

I am unwilling to publish the tutorial with an example we are not confident in.

**Comment by yatil** [comment]
BTW: The images are deliberately distractive to drive the point about good contrasts and stopping the animation home. Carousels like this are common “in the wild”.

**Comment by yatil** [comment]
@bakkenb & @slhenry Can you review the [proposal here](https://w3c.github.io/wai-tutorials/carousels/working-example/) and comment if this is ok or give more input. Thank you.

**Comment by bakkenb** [comment]
Might be best to leave as is for now and concentrate on getting it out the door. I am not too find of the space/galaxy photos either. As stated earlier in my other comment. I would like to have some discussion around it first, then if the whole group feels strongly about needing a change, we can look into options then. That way we don't hold up the publication.

The space teddy is fine for now and it works and is complete. We can consider changing it later.

**Comment by sharronrush** [comment]
I like space teddy...prefer to leave it in place.

**Comment by yatil** [comment]
I have reverted the change.

**Comment by AndrewArch** [comment]
I'm happy with space teddy too - adds a bit of lightness to the site :)

**Comment by slhenry** [comment]
I'm fine with lightness & fun, I just find this the wrong tone and too visually distracting. For example, [BAD ](https://www.w3.org/WAI/demos/bad/after/home.html) has very clever and funny stuff, and it just feels more appropriate.

**Comment by shwetank** [comment]
I don't have a particular problem with the space teddy example as such. As a developer, I'm just interested in the code and the way things work, not the content of the images etc (unless they are somehow nsfw, which is certainly not the case here).

However, just as a suggestion, given the discussion here, I would like to propose the following: 

Most carousals in the wild deal with content which is fast moving in nature (like news, or articles which are featured for a while and then unfeatured relatively quickly, like a few days or even hours later etc). So maybe we could have a carousal with images of news (in order to not make it political, maybe take sports as a topic?). For example, if we can find 3-4 royalty free images of say, the olympics, then we can use those to make a sample carousal. 

That topic could be probably a bit more in tune with what developers would be familiar with in the real world. 

Just a suggestion, and as stated earlier, i'm ok with the teddy too. :)

**Comment by brianelton** [comment]
Discussed with @shawna-slh and @lakeen and we decided this can be closed.
