### ISSUE TITLE
[Mobile Overview] Scope

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#475]
I am unclear how that tutorial would relate to the Mobile Overview, and would rather like to have mobile information interlaced with other tutorial content. Most web work is responsive these days, and touch screens  for examples are in not-so-mobile contexts like tablets or laptops as well. Even some desktops have touch input these days. I think the tutorial – as it sounds like from the outline – is a bit too spec focused.

What about:

* Update the mobile Overview page.
* Put a practical mobile component into the tutorials, like an off-page menu, or touch support for the carousel.
* Interlink the different resources.

**Comment by brewerj** [comment]
Reply as of 20170331: 
How would relate to Mobile Overview: do you mean how this would related to the Mobile Accessibility resource page? <http://www.w3.org/WAI/mobile> Ideally a mobile overview tutorial and/or guide, would be more hands-on, and complementary to the Mobile Accessibility resource page, which seems more like an annotated reference list.
Interlacing all new mobile content: Still think that mobile developers would still have difficulty discovering the integrated material, unless we also created a landing page for that among the tutorials, which already have a reliably good draw. So, integrated would be nice, but wouldn't a collection of integrated examples that we attract people to with a "mobile accessibility" label, help draw people to a place where they could get introduced to the integrated solutions? 

+1 to updating the mobile accessibility resource page.
+1 to integrating mobile components.
+10 to integrating the different resources; that's what I'm hoping for.

**Comment by patrickhlauke** [comment]
lacking overall context, i would say this: as @yatil points out, many of the traditional technologies that people seem to lump together under the umbrella term "mobile" are actually available across a variety of form factors and devices (mobile, tablet, phablet, laptop, dekstop, set-top boxes, etc).

one far more extensible and future-proof approach would be, in my mind, to create individual pieces of advice related around specific technologies/factors, such as: a tutorial on how to make content touchscreen friendly, a tutorial on how to adapt content to a small screen/viewport, a tutorial on how additional sensors (e.g. accelerometer, tilt, light sensor, etc) can be used. these would focus purely on the technology itself. THEN provide overview pages for what people generally categorise devices into, such as "tutorials for mobile/tablet development", with introductory text explaining that these typically feature touchscreens, sensors, small screens, and then link to the tech specific tutorials.

this way, it's easier later on to also note on a "desktop/laptop" specific page, that more and more devices (particularly laptops) also feature touchscreens, and then cross-link to the same touchscreen tutorial.

otherwise, this reopens the whole "there is no desktop web, there is no mobile web, there is just the web" debate which the web development community settled already about 10 years or so ago (along the same lines as the "there is no fold" discussion)

**Comment by yatil** [comment]
This issue was moved to w3c/wai-mobile-intro#27
