### ISSUE TITLE
[Accessible Media Tutorial] Auto Generated Captions Page 3

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#506]
Just a simple question about the section titled "Using automatic captions responsibly."

Is there a better free automatic captioning service than YouTube that we can recommend? Isn't there a lot of problems with YouTube's service being very inaccurate? Not sure if there is a better **_free_** tool out there, but if there is then maybe we can point to that instead.

**Comment by gfreedncam** [comment]
Yes, there are TONS of problems with YouTube's speech-to-text accuracy.  I will stop there.

There are some broadcast-level speech-to-text tools that can be used to transcribe and timestamp, similar to what YT is doing.  Their accuracy *may* be higher (I can't say because I have not used them), but they're not for the average user and they're definitely not for DIY captioning.  Maybe what I should do is rewrite this to be non-specific, yet still make clear the perils and benefits of using STT tools for captioning?

**Comment by brewerj** [comment]
After reflection, Geoff left in the current YT example, along with the generic workflow. And it looks to me that the perils and benefits of using STT tools are clear. Closing...
