### ISSUE TITLE
[Accessible Media Tutorial] - Name

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#512]
After some short discussion with some members of the planning team, I am starting to question the idea of calling this content a Tutorial. There is a lot of good information being put in this resource, much more than what is in a typical Web Accessibility Tutorial. 

I feel all of the content is good and should stay in, but it does not follow the simplistic presentation of our current tutorials. I would like us to reconsider the name of this resource to make it more clear of what it is. If renamed, it could also be more in alignment with what we are thinking for the ARIA and the Mobile resources.

Suggested name: **Accessible Media Production Guide**

**Comment by sharronrush** [comment]
Yes, on today's call we all agreed that this resource is not a tutorial as we have defined and used it so far.  Our tutorials are short, focused pieces on just one subject. This media resource is broader and will be more extensive. best to use the alternative title and not risk confusing people about the intent and scope of the resource.

**Comment by James-Green** [comment]
I really like Brent's suggested name.

**Comment by sharronrush** [comment]
By changing these resources from "Tutorials" to "Guides" we distinguish them and acknowledge their related but different approach and function.

**Comment by kakinney** [comment]
I agreed with this during the meeting.  This is much larger than our tutorial style and calling it a Guide seems more appropriate.

**Comment by nrhsinclair** [comment]
Yes, I agree, this is much more a guide than a tutorial.

**Comment by dboudreau** [comment]
I lean towards the same direction.

**Comment by yatil** [comment]
I agree, I also think for a tutorial, it should be more hands-on in terms of implementation. That’s something I brought up in #478.

**Comment by brewerj** [comment]
A few thoughts ahead of our discussion in EOWG meeting in a few hours. 
- I've discussed this with Geoff and we're both hoping and intending that this will look more like the other tutorials by the time it's done, including being more hands-on.
- From a devil's-advocate perspective -- perhaps the more we maintain a narrow definition of what each resource type is, the more we may make it harder for people to know what to look for, so we may impede the discoverability of relevant resources. We may be able to make up for some of that with the improved WAI resource search capabilities that we're also working on; however, the tutorials are become better known, and we'd hoped to take advantage of the self-reinforcing marketing aspect having this be one of the tutorials. This resource would miss out on that.
- Might it make sense to hold off the naming decision till the rest of the newer tutorials/developers' intros are more mature, since we were also probably going to name those differently? If we're introducing multiple new flavors of names for these types of resources, won't that be more confusing for people who are seeking info? (The lastest leading title for that was "A Developers' Intro to ... " which I don't think would work for this one.)
I guess another way to say this is, might the categorization of types of supporting resources & naming conventions be less of an issue to the potential users of these documents, who might be more interested in seamless access to the topics of their choice?
Just some different thoughts for now. I look forward to the discussion.

**Comment by yatil** [comment]
> From a devil's-advocate perspective -- perhaps the more we maintain a narrow definition of what each resource type is, the more we may make it harder for people to know what to look for, so we may impede the discoverability of relevant resources. We may be able to make up for some of that with the improved WAI resource search capabilities that we're also working on; however, the tutorials are become better known, and we'd hoped to take advantage of the self-reinforcing marketing aspect having this be one of the tutorials. This resource would miss out on that.

From a devil’s-devil’s-advocate perspective: Are the tutorials such a draw because they are so narrowly defined and people know to expect? And if they are, don’t we water down our message of them when we label stuff tutorials that are no tutorials, or at least have a different focus?

**Comment by nrhsinclair** [comment]
There are many types of resources on the WAI site. The Accessible Media information in development is an excellent resource that should not be cut back in any way. Perhaps it fits under Getting Started with Accessibility, Accessibility Basics: https://www.w3.org/WAI/gettingstarted/ many types of overview and introductory information found there. 

Additional accessible media tutorials on creating timed text files and open source resources would be helpful. People have the expectation that a tutorial will provide step-by-step instructions.

**Comment by brewerj** [comment]
Just reflecting back on discussion at EOWG f2f meeting, I believe we agreed to leave this as is for now (currently marked "tutorial") and to re-check titles for all of this new set of resources after they're done, and after the website redesign is done as well. (And noting also for the record, that the other new resources were aiming for dev's intro, not dev's guide, which is not as good a uniform match.
