### ISSUE TITLE
proposal to add colorblind-media project for enhancing web media accessibility for color vision deficiencies

### ISSUE THREAD

**Issue by akhileshthite** [w3c/wai-tutorials#769]
I would like to propose the inclusion of the [Colorblind Media](https://akhileshthite.github.io/colorblind-media/) project to enhance web media accessibility for individuals with color vision deficiencies. However, I'm uncertain about the most appropriate section or repository for this contribution. Could you please advise on where this project could best be integrated or referenced?

https://github.com/akhileshthite/colorblind-media

**Comment by brianelton** [comment]
Thanks for your proposal @akhileshthite. While your project seems very interesting, unfortunately this is not something that we would include in the WAI Tutorials resource. The purpose of the tutorials is to aid in creating accessible websites from the beginning so that tools like yours, that aid in consuming **inaccessible** web content, are not needed.
This is not to say that your tool is not needed! It just doesn't fit within the scope of the tutorials.
